subarch: amd64
target: stage3
version_stamp: musl-llvm-@TIMESTAMP@
rel_type: musl-llvm
profile: default/linux/amd64/17.0/musl/llvm-toolchain
snapshot: @TIMESTAMP@
source_subpath: musl/stage1-amd64-musl-llvm-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: clang-musl
compression_mode: pixz
